import GT from "../assets/GT.jpg";
import TSF from "../assets/TSF.jpg";

export const Card = [
  {
    title: "2023",
    subTitle: "Ground Truthing",
    description: "Enabling Works",
    role: "Portion 1A",
    btn: "READ MORE",
    activity: "Ground Truthing",
    detail:
      "Ground truthing in the context of a Knowledge Extraction and Reuse Project (KERP) refers to the process of validating and verifying the accuracy of the extracted information or data against a known and reliable set of reference data, often referred to as the 'ground truth.' This process ensures that the information extracted by the KERP system is accurate and reliable.",
    img: GT,
  },
  {
    title: "Date",
    subTitle: "Activity",
    description: "Portion Type",
    role: "Portion #",
    btn: "Example...",
    activity: "TSF",
    detail: "Example...",
    img: TSF,
  },
  {
    title: "Date",
    subTitle: "Activity",
    description: "Portion Type",
    role: "Portion #",
    btn: "Example...",
    activity: "Test",
    detail: "Example...",
    img: TSF,
  },
  {
    title: "Date",
    subTitle: "Activity",
    description: "Portion Type",
    role: "Portion #",
    btn: "Example...",
    activity: "Test",
    detail: "Example...",
    img: TSF,
  },
  {
    title: "Date",
    subTitle: "Activity",
    description: "Portion Type",
    role: "Portion #",
    btn: "Example...",
    activity: "Test",
    detail: "Example...",
    img: TSF,
  },
  {
    title: "Date",
    subTitle: "Activity",
    description: "Portion Type",
    role: "Portion #",
    btn: "Example...",
    activity: "Test",
    detail: "Example...",
    img: TSF,
  },
  {
    title: "Date",
    subTitle: "Activity",
    description: "Portion Type",
    role: "Portion #",
    btn: "Example...",
    activity: "Test",
    detail: "Example...",
    img: TSF,
  },
  {
    title: "Date",
    subTitle: "Activity",
    description: "Portion Type",
    role: "Portion #",
    btn: "Example...",
    activity: "Test",
    detail: "Example...",
    img: TSF,
  },
  {
    title: "Date",
    subTitle: "Activity",
    description: "Portion Type",
    role: "Portion #",
    btn: "Example...",
    activity: "Test",
    detail: "Example...",
    img: TSF,
  },
  {
    title: "Date",
    subTitle: "Activity",
    description: "Portion Type",
    role: "Portion #",
    btn: "Example...",
    activity: "Test",
    detail: "Example...",
    img: TSF,
  },
  {
    title: "Date",
    subTitle: "Activity",
    description: "Portion Type",
    role: "Portion #",
    btn: "Example...",
    activity: "Test",
    detail: "Example...",
    img: TSF,
  },
  {
    title: "Date",
    subTitle: "Activity",
    description: "Portion Type",
    role: "Portion #",
    btn: "Example...",
    activity: "Test",
    detail: "Example...",
    img: TSF,
  },
];
